import { useState } from "react";
import Head from "next/head";
import { Logo } from "@components/icons";
import LoginForm from "@components/auth-forms/login-form";
import SignUpForm from "@components/auth-forms/signup-form";
import styles from "@components/auth-forms/auth-forms.module.css";

const AuthForms = ({ screen = "signup" }) => {
  const [form, setForm] = useState(screen);

  return (
    <>
      <div className={styles.authModal}>
        <Head>
          <title>
            {form == "login" ? "Log In" : "Sign Up"} - Cakrawala Achieve
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-196x196.png"
            sizes="196x196"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-96x96.png"
            sizes="96x96"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-32x32.png"
            sizes="32x32"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-16x16.png"
            sizes="16x16"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-128.png"
            sizes="128x128"
          />
        </Head>

        <Logo className={styles.logo} />

        {form === "login" ? <LoginForm /> : <SignUpForm />}

        {form === "login" ? (
          <div className={styles.authSwichMessage}>
            Don’t have an account?{" "}
            <button className="text-blue-600" onClick={() => setForm("signup")}>
              Sign up
            </button>
          </div>
        ) : (
          <div className={styles.authSwichMessage}>
            Already have an account?{" "}
            <button className="text-blue-600" onClick={() => setForm("login")}>
              Log in
            </button>
          </div>
        )}
      </div>
    </>
  );
};

export default AuthForms;
