import Head from "next/head";
import QuestionAskView from "@components/question-ask-view";
import Header from "@components/layout/header";
import QuestionForm from "@components/question-ask-view/question-form";

const Ask = () => {
  return (
    <>
      <div>
        <Head>
          <title>Ask a Question - Cakrawala Achieve</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-196x196.png"
            sizes="196x196"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-96x96.png"
            sizes="96x96"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-32x32.png"
            sizes="32x32"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-16x16.png"
            sizes="16x16"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-128.png"
            sizes="128x128"
          />
        </Head>
        <Header />
        <QuestionAskView>
          <QuestionForm />
        </QuestionAskView>
      </div>
    </>
  );
};

export default Ask;
