import { useEffect, useState } from "react";
import Head from "next/head";
import { publicFetch } from "@utils/service";
import Layout from "@components/layout";
import PageTitle from "@components/page-title";
import SearchInput from "@components/search-input";
import UserList from "@components/user-list";
import UserItem from "@components/user-list/user-item";
import { Spinner } from "@components/icons";

function UsersPage() {
  const [searchTerm, setSearchTerm] = useState(null);
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (searchTerm === null) {
      const fetchUser = async () => {
        const { data } = await publicFetch.get("/users");
        setUsers(data);
      };

      fetchUser();
    } else {
      const delayDebounceFn = setTimeout(async () => {
        setLoading(true);
        const { data } = await publicFetch.get(
          searchTerm ? `/users/${searchTerm}` : `/users`
        );
        setUsers(data);
        setLoading(false);
      }, 500);

      return () => clearTimeout(delayDebounceFn);
    }
  }, [searchTerm]);

  return (
    <>
      <Layout extra={false}>
        <Head>
          <title>Users - Cakrawala Achieve</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-196x196.png"
            sizes="196x196"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-96x96.png"
            sizes="96x96"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-32x32.png"
            sizes="32x32"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-16x16.png"
            sizes="16x16"
          />
          <link
            rel="icon"
            type="image/png"
            href="/icon/favicon-128.png"
            sizes="128x128"
          />
        </Head>

        <PageTitle title="Users" borderBottom={false} />

        <SearchInput
          placeholder="Search by user"
          isLoading={loading}
          autoFocus
          autoComplete="off"
          type="text"
          onChange={(e: any) => setSearchTerm(e.target.value)}
        />

        {!users && (
          <div className="loading">
            <Spinner />
          </div>
        )}

        {users && (
          <>
            <UserList>
              {users?.map(({ username, profilePhoto, created, id }: any) => (
                <UserItem
                  key={id}
                  username={username}
                  profilePhoto={profilePhoto}
                  created={created}
                />
              ))}
            </UserList>

            {users.length == 0 && (
              <div className="not-found">No users matched your search.</div>
            )}
          </>
        )}
      </Layout>
    </>
  );
}

export default UsersPage;
